# Generated by Django 5.2.7 on 2025-10-07 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='added_tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at_date', models.DateTimeField(default=datetime.date.today)),
                ('created_at_time', models.TimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='completed_tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at_date', models.DateTimeField()),
                ('created_at_time', models.TimeField()),
                ('in_progress_at_date', models.DateTimeField()),
                ('in_progress_at_time', models.TimeField()),
                ('completed_at_date', models.DateTimeField(default=datetime.date.today)),
                ('completed_at_time', models.TimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='in_progress_tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at_date', models.DateTimeField()),
                ('created_at_time', models.TimeField()),
                ('in_progress_at_date', models.DateTimeField(default=datetime.date.today)),
                ('in_progress_at_time', models.TimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
