# Generated by Django 5.2.7 on 2025-10-07 17:03

import datetime
import manegement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manegement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='added_tasks',
            name='created_at_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='added_tasks',
            name='created_at_time',
            field=models.TimeField(default=manegement.models.current_time),
        ),
        migrations.AlterField(
            model_name='completed_tasks',
            name='completed_at_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='completed_tasks',
            name='completed_at_time',
            field=models.TimeField(default=manegement.models.current_time),
        ),
        migrations.AlterField(
            model_name='completed_tasks',
            name='created_at_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='completed_tasks',
            name='in_progress_at_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='in_progress_tasks',
            name='created_at_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='in_progress_tasks',
            name='in_progress_at_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='in_progress_tasks',
            name='in_progress_at_time',
            field=models.TimeField(default=manegement.models.current_time),
        ),
    ]
