# Generated by Django 5.2.7 on 2025-10-07 17:29

import datetime
import manegement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manegement', '0002_alter_added_tasks_created_at_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='removed_tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at_date', models.DateField()),
                ('created_at_time', models.TimeField()),
                ('in_progress_at_date', models.DateField()),
                ('in_progress_at_time', models.TimeField()),
                ('completed_at_date', models.DateField()),
                ('completed_at_time', models.TimeField()),
                ('removed_at_date', models.DateField(default=datetime.date.today)),
                ('removed_at_time', models.TimeField(default=manegement.models.current_time)),
            ],
        ),
    ]
