# Generated by Django 5.2.7 on 2025-10-12 03:48

import comments.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at_date', models.DateField(default=datetime.date.today)),
                ('created_at_time', models.TimeField(default=comments.models.current_time)),
            ],
        ),
    ]
