# Generated by Django 5.2.7 on 2025-10-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='description',
        ),
        migrations.AddField(
            model_name='comment',
            name='subject',
            field=models.CharField(default='Default Subject', max_length=100),
            preserve_default=False,
        ),
    ]
